/* included by renderer-gl3.c -- do not compile separately */
static const char *vshader_gbuffer_src =
"#version 330\n"
"layout(std140) uniform scene {\n"
"  mat4 mvmatrix;\n"
"  mat4 mvpmatrix;\n"
"  mat4 ipmatrix;\n"
"};\n"
"in vec3 vposition;\n"
"in vec2 vtexcoord;\n"
"in vec3 vnormal;\n"
"in vec4 vtangent;\n"
"smooth out float fdepth;\n"
"smooth out vec2 ftexcoord;\n"
"smooth out mat3 tbnmatrix;\n"
"void main() {\n"
"  fdepth    = -(mvmatrix * vec4(vposition, 1)).z;\n"
"  ftexcoord = vtexcoord;\n"
"\n"
"  vec3 vbitangent = cross(vnormal, vtangent.xyz) * vtangent.w;\n"
"  tbnmatrix = mat3(mvmatrix[0].xyz, mvmatrix[1].xyz, mvmatrix[2].xyz) * mat3(vtangent.xyz, vbitangent, vnormal);\n"
"\n"
"  gl_Position = mvpmatrix * vec4(vposition, 1);\n"
"}\n";

static const char *fshader_gbuffer_src =
"#version 330\n"
"uniform sampler2D tdiffuse;\n"
"uniform sampler2D tnormal;\n"
"uniform sampler2D tspecular;\n"
"uniform sampler2D temissive;\n"
"smooth in float fdepth;\n"
"smooth in vec2  ftexcoord;\n"
"smooth in mat3  tbnmatrix;\n"
"out float gdepth;\n"
"out vec4  gdiffuse;\n"
"out vec2  gnormal;\n"
"out vec4  gspecular;\n"
"out vec4  gemissive;\n"
"void main() {\n"
"  vec3 n_local = texture(tnormal, ftexcoord).xyz * 2.0 - 1.0;\n"
"  vec3 n_world = normalize(tbnmatrix * n_local);\n"
"\n"
"  gdepth    = fdepth;\n"
"  gdiffuse  = texture(tdiffuse, ftexcoord);\n"
"  gnormal   = n_world.xy;\n"
"  gspecular = texture(tspecular, ftexcoord);\n"
"  gemissive = texture(temissive, ftexcoord);\n"
"}\n";

static const char *vshader_pointlight_src = 
"#version 330\n"
"layout(std140) uniform scene {\n"
"  mat4 mvmatrix;\n"
"  mat4 mvpmatrix;\n"
"  mat4 ipmatrix;\n"
"};\n"
"layout(std140) uniform pointlight {\n"
"  vec3  position;\n"
"  vec3  color;\n"
"  float intensity;\n"
"};\n"
"in vec3 vcoord;\n"
"smooth out vec2 ftexcoord;\n"
"void main () {\n"
"  float radius = 32.0 / sqrt(intensity);\n"
"  vec4  coord  = vec4(vcoord * radius, 1.0);\n"
"  ftexcoord    = (mvmatrix * coord).xy * 0.5 + 0.5;\n"
"  gl_Position  = mvpmatrix * coord;\n"
"}\n";

static const char *fshader_pointlight_src =
"#version 330\n"
"layout(std140) uniform scene {\n"
"  mat4 mvmatrix;\n"
"  mat4 mvpmatrix;\n"
"  mat4 ipmatrix;\n"
"};\n"
"layout(std140) uniform pointlight {\n"
"  vec3  position;\n"
"  vec3  color;\n"
"  float intensity;\n"
"};\n"
"uniform sampler2D tdepth;\n"
"uniform sampler2D tdiffuse;\n"
"uniform sampler2D tnormal;\n"
"uniform sampler2D tspecular;\n"
"smooth in ftexcoord;\n"
"out vec4 color;\n"
"void main () {\n"
"  float depth = texture(tdepth, ftexcoord).r;\n"
"  vec3  coord = (ipmatrix * vec4(ftexcoord * 2.0 - 1.0, depth, 1.0)).xyz;\n"
"  float dist  = distance(position, coord);\n"
"  float luminance = intensity / (dist * dist);\n"
""
"  vec3 norm;\n"
"  norm.xy = texture(tnormal, ftexcoord).xy;\n"
"  norm.z  = sqrt(1.0 - dot(norm.xy, norm.xy));\n"
""
"  vec3 diff = texture(tdiffuse, ftexcoord).rgb;\n"
"  vec4 spec = texture(tspecular, ftexcoord);\n"
"  color.rgb = luminance * diff * dot(norm, vec3(0.0, 0.0, 1.0)) + luminance * spec.rgb * pow(dot(norm, vec3(0.0, 0.0, 1.0)), spec.a*255.0);\n"
"  color.a   = 1.0;\n"
"}\n";

/* to decode rgbe emissive value: glow.rgb * exp2(glow.a * 16.0 - 8.0) */

static const char *vshader_tonemap_src = 
"#version 330\n"
"in vec2 vcoord;\n"
"smooth out vec2 ftexcoord;\n"
"void main () {\n"
"  ftexcoord = vcoord;\n"
"  gl_Position = vec4(vcoord * 2.0 - 1.0, 0.0, 1.0);\n"
"}\n";

static const char *fshader_tonemap_src = 
"#version 330\n"
"uniform sampler2D tcomposite;\n"
"smooth in vec2 ftexcoord;\n"
"out vec4 color;\n"
"void main() {\n"
"  vec3 c = texture(tcomposite, ftexcoord).rgb;\n"
"  color = vec4(1.0 / (1.0 + exp(-8.0 * pow(c, vec3(0.8)) + 4.0)) - 0.018, 1.0);\n"
"}\n";

static const char *vshader_blit_src =
"#version 330\n"
"uniform vec2 size;\n"
"uniform vec2 offset;\n"
"in vec2 vcoord;\n"
"smooth out vec2 ftexcoord;\n"
"void main () {\n"
"  ftexcoord = vcoord;\n"
"  gl_Position = vec4(vcoord * size + offset, 0.0, 1.0);\n"
"}\n";

static const char *fshader_blit_src = 
"#version 330\n"
"uniform sampler2D image;\n"
"smooth in vec2 ftexcoord;\n"
"out vec4 color;\n"
"void main() {\n"
"  color = texture(image, ftexcoord);\n"
"}\n";

